### ISSUE TITLE
[Feat] Add Bug Report Template

### ISSUE THREAD

**Issue by abhishekHegde2000** [heysagnik/zentask#12]
**Description:**
Add a Bug Report template to streamline the reporting process for issues found in the project.

**Tasks:**
1. **Create Template:**
   - Define sections for describing the issue, expected behavior, actual behavior, and steps to reproduce.
   - Include guidelines for contributors to follow when submitting bug reports.

**Files to Modify:**
- Create `.github/ISSUE_TEMPLATE/bug-report.md`

**Benefits:**
- Improves clarity and consistency in bug reports.
- Facilitates quicker identification and resolution of issues within the project.

**Comment by abhishekHegde2000** [comment]
@heysagnik, can you please assign this task to me as part of Hacktoberfest?

**Comment by heysagnik** [comment]
But this won't be counted
