### ISSUE TITLE
Change the title.

### ISSUE THREAD

**Issue by Sriijannn** [heysagnik/zentask#4]
Presently the hosted page shows a title "Create Next App", it'll be better if it says "Zentask" instead.

**Comment by coderhs** [comment]
@Sriijannn I can send a PR for this? I also see there is an option for description. Do you have any recommendations or shall i put `A time-management tool that helps prioritize tasks based on their urgency and importance.`

```tsx
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
```
