### ISSUE TITLE
Refractor code in method.jsx 

### ISSUE THREAD

**Issue by mohitahlawat2001** [heysagnik/zentask#6]
Making it more modular , making more subfile from this single file

**Comment by heysagnik** [comment]
@mohitahlawat2001 you may proceed

**Comment by njaina** [comment]
is there any issue like this? can you assign it to me?

**Comment by heysagnik** [comment]
@mohitahlawat2001 what's the progress

**Comment by mohitahlawat2001** [comment]
doing @heysagnik
