### ISSUE TITLE
Time setting field is not much user friendly 

### ISSUE THREAD

**Issue by Prithwi32** [heysagnik/zentask#9]
Currently looking like: 
![Screenshot_2024-10-03-22-41-53-707_com android chrome](https://github.com/user-attachments/assets/22f17e57-1867-4d67-b904-320948352f20)

I like to contribute as: 
![download](https://github.com/user-attachments/assets/a827de5f-0fa4-4925-9088-119da3d82de5)

**Comment by Prithwi32** [comment]
@heysagnik could u assign this task to me under hacktoberfest

**Comment by heysagnik** [comment]
@Prithwi32 assigned you
